# Site settings
title: Solace Java API (JCSMP)
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-java"
repository: https://github.com/SolaceSamples/solace-samples-java

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Link
links-get-started: //dev.solace.com/get-started/java-tutorials/
links-downloads: //solace.com/downloads/
links-community: //solace.community
docs-core-concepts: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-psplus-manager: //docs.solace.com/Solace-PubSub-Manager/PubSub-Manager-Overview.htm
docs-semp-api: //docs.solace.com/SEMP/Using-SEMP.htm
docs-endpoints: docs.solace.com/PubSub-Basics/Endpoints.htm
docs-api-ref: //docs.solace.com/API-Developer-Online-Ref-Documentation/java/index.html
docs-gm-rr: //docs.solace.com/Solace-Messaging-APIs/Request-Reply-Messaging.htm
docs-topic-queue: //docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-client-profile: //docs.solace.com/Configuring-and-Managing/Configuring-Client-Profiles.htm
docs-client-profile-allow-transacted: //docs.solace.com/Configuring-and-Managing/Configuring-Client-Profiles.htm#Allow-Trans-Sess
docs-client-profile-allow-g-receives: //docs.solace.com/Configuring-and-Managing/Configuring-Client-Profiles.htm#Allow-G-Msg-Receives
docs-client-profile-allow-g-creates: //docs.solace.com/Configuring-and-Managing/Configuring-Client-Profiles.htm#Allow-G-Msg-Creates
links-solaceCloud-setup: //solace.com/cloud/
docs-api-endpoints: //docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/EndpointProperties.html
docs-replay-use-cases: //docs.solace.com/Configuring-and-Managing/Message-Replay.htm
docs-replay-cli-config: //docs.solace.com/Configuring-and-Managing/Msg-Replay-Config.htm
