# Site settings
title: Solace Java API (JCSMP)
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-java"
repository: https://github.com/SolaceSamples/solace-samples-java

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-get-started: //dev.solace.com/get-started/java-tutorials/
links-downloads: //dev.solace.com/downloads/
links-community: //dev.solace.com/community/
docs-vmr-setup: //docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: //docs.solace.com/Features/Core-Concepts.htm
docs-endpoints: //docs.solace.com/Features/Core-Concepts.htm#endpoints
docs-api-ref: //docs.solace.com/API-Developer-Online-Ref-Documentation/java/index.html
docs-gm-rr: //docs.solace.com/Solace-Messaging-APIs/Request-Reply-Messaging.htm
docs-topic-queue: //docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-client-profile: //docs.solace.com/Features/Core-Concepts.htm#client-profile
links-solaceCloud-setup: //cloud.solace.com/create-messaging-service/
docs-api-endpoints: //docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/EndpointProperties.html
solace-apis-dev:
  - value: //dev.solace.com/get-started/c-tutorials/
    name: C
  - value: //dev.solace.com/get-started/dotnet-tutorials/
    name: C#/.NET
  - value: //dev.solace.com/get-started/java-tutorials/
    name: Java
  - value: //dev.solace.com/get-started/java-rto-tutorials/
    name: Java RTO
  - value: //dev.solace.com/get-started/javascript-tutorials/
    name: JavaScript
  - value: //dev.solace.com/get-started/node-js-tutorials/
    name: Node.js
open-apis-dev:
  - value: //dev.solace.com/get-started/amqp-tutorials-jms-11/
    name: AMQP - JMS 1.1
  - value: //dev.solace.com/get-started/amqp-tutorials-jms-2/
    name: AMQP - JMS 2.0
  - value: //dev.solace.com/get-started/amqp-tutorials-node-js/
    name: AMQP - Node.js
  - value: //dev.solace.com/get-started/mqtt-tutorials/
    name: MQTT - Eclipse Paho Java
  - value: //dev.solace.com/get-started/amqp-tutorials-jms-11/
    name: JMS 1.1 - Apache Qpid
  - value: //dev.solace.com/get-started/amqp-tutorials-jms-2/
    name: JMS 2.0 - Apache Qpid
  - value: //dev.solace.com/get-started/jms-tutorials/
    name: JMS 1.1 - Solace
  - value: //dev.solace.com/get-started/openmama-tutorials/
    name: OpenMAMA
  - value: //dev.solace.com/get-started/rest-tutorials/
    name: REST Messaging
other-environments-dev:
  - value: //dev.solace.com/get-started/pcf-tutorials/
    name: Pivotal Cloud Foundry

solace-apis-cloud:
  - value: //cloud.solace.com/samples/solace-samples-c/
    name: C
  - value: //cloud.solace.com/samples/solace-samples-dotnet/
    name: C#/.NET
  - value: //cloud.solace.com/samples/solace-samples-java/
    name: Java
  - value: //cloud.solace.com/samples/solace-samples-javarto/
    name: Java RTO
  - value: //cloud.solace.com/samples/solace-samples-javascript/
    name: JavaScript
  - value: //cloud.solace.com/samples/solace-samples-nodejs/
    name: Node.js
open-apis-cloud:
  - value: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms1/
    name: AMQP - JMS 1.1
  - value: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms2/
    name: AMQP - JMS 2.0
  - value: //cloud.solace.com/samples/solace-samples-amqp-nodejs/
    name: AMQP - Node.js
  - value: //cloud.solace.com/samples/solace-samples-mqtt/
    name: MQTT - Eclipse Paho Java
  - value: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms1/
    name: JMS 1.1 - Apache Qpid
  - value: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms2/
    name: JMS 2.0 - Apache Qpid
  - value: //cloud.solace.com/samples/solace-samples-jms/
    name: JMS 1.1 - Solace
  - value: //cloud.solace.com/samples/solace-samples-openmama/
    name: OpenMAMA
  - value: //cloud.solace.com/samples/solace-samples-rest-messaging/
    name: REST Messaging

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
