# Site settings
title: Solace Messaging API for Java (JCSMP)
baseurl: "/solace-samples-java" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-java

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-get-started: http://dev.solace.com/get-started/java-tutorials/
links-downloads: http://dev.solace.com/downloads/
links-community: http://dev.solace.com/community/
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-endpoints: http://docs.solace.com/Features/Core-Concepts.htm#endpoints
docs-api-ref: http://docs.solace.com/API-Developer-Online-Ref-Documentation/java/index.html
docs-gm-rr: http://docs.solace.com/Solace-Messaging-APIs/Request-Reply-Messaging.htm
docs-topic-queue: http://docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-client-profile: http://docs.solace.com/Features/Core-Concepts.htm#client-profile

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
